version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - pg
    environment:
      - DATABASE_URL=postgres://postgres:postgres@pg:5432/postgres

  pg:
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=postgres

volumes:
  pg-data:
